version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_password
    ports:
      - 27017:27017

  webserver:
    image: apache/airflow:2.2.3
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - 8080:8080

  scheduler:
    image: apache/airflow:2.2.3
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  worker:
    image: apache/airflow:2.2.3
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: airflow
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  mongo_data:
  pg_data:
